'use client';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppContext from "./AppContext";
import { PRODUCTS } from "./utils/constant";
import React from "react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [products, setProducts] = React.useState(PRODUCTS);
  const [cart, setCart] = React.useState([]);
  const [total, setTotal] = React.useState(0);

  const defaultValue = {
    products,
    setProducts,
    cart,
    setCart,
    total,
    setTotal,
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppContext.Provider value={defaultValue}>
          {children}
        </AppContext.Provider>
      </body>
    </html>
  );
}
